apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: odoo-ns
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
          - name: POSTGRES_USER
            value: toto
          - name: POSTGRES_PASSWORD
            value: toto
          - name: POSTGRES_DB
            value: "postgres"
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: pgdata
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: pg-claim 
