apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
  namespace: odoo-ns
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data-pv
