apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-claim
  namespace: odoo-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 100Mi
